version: '3.1'
services:
  db:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: testdb
    ports:
      - 5432:5432